#pragma once

module idl_msg{

  enum GripperType {
    grip_rot,
    grip_lin,
    grip_rotlin
  };

  struct GripCmd_msg {
    GripperType gripper;
    int32 servo_1_deg;
    int32 servo_2_deg;
    int32 servo_3_deg;
    boolean trigger_gripper;
    boolean request_sensor;
  };

};
