#pragma once

#include "Header_msg.idl"
#include "Vector3f_msg.idl"
#include "Euler_angle_msg.idl"

module idl_msg{

struct Mocap_msg {

  Header_msg header;

  boolean occluded;

  Vector3f_msg position;

  Euler_angle_msg orientation;

  float latency;
};

};